### ISSUE TITLE
Conceal crash

### ISSUE THREAD

**Issue by McyD** [Tyrsis/EssentialsPlugin#45]
It seems if another method is used to cleanup the server, such as SE Toolbox, missing concealed entities cause a crash on start-up.

http://pastebin.com/akEtaj8v

Using newest version .989.  As a workaround, disabling conceal allows the server to load.

**Comment by Tyrsis** [comment]
This should hopefully be addressed in the next update

**Comment by LordNex** [comment]
Still crashing

http://paste.ee/p/xd3xv

**Comment by dodexahedron** [comment]
This seems to be more reliable, now, though it still throws NullReferenceExceptions (but does not bring the server down).

2015-01-05 04:41:00.419 - Thread: 5 -> ConcealEntity(2): System.NullReferenceException: Object reference not set to an instance of an object.
   at EssentialsPlugin.Utility.EntityManagement.<>c__DisplayClass6.<ConcealEntity>b__5()

**Comment by Tyrsis** [comment]
This should be fixed in next version going up today.
