### ISSUE TITLE
 v1.0.2.1652 - Dynamic Entity Management - Projected Image fully built on reveal

### ISSUE THREAD

**Issue by EngineerBean** [Tyrsis/EssentialsPlugin#73]
A player has brought to my attention that if a projector is left on when it is concealed. When revealed the projected image is fully built.

**Comment by demolish50** [comment]
I have had reports of this on my server as well. I did not know how to re-produce. I was able to do so with this info, so confirmed!

**Comment by Tyrsis** [comment]
This should be fixed in last version.

**Comment by demolish50** [comment]
I'm getting reports that this is still occurring, I have not been able to verify.

**Comment by Tyrsis** [comment]
If it's still happening then it's unavoidable.  The only way to detect projections is to check if the object has any physics.  I am doing that now, so I will need more information if it's still occuring.
